service: landsat-mosaic-tiler

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'production'}
  region: us-west-2
  deploymentBucket: ${opt:bucket}
  httpApi:
    cors: true

  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "*"
     Resource:
       - arn:aws:s3:::${opt:bucket}*

  -  Effect: "Allow"
     Action:
       - "s3:*"
     Resource:
       - "arn:aws:s3:::landsat-pds*"

  apiGateway:
    binaryMediaTypes:
      - '*/*'
    minimumCompressionSize: 1

package:
  artifact: package.zip

functions:
  tiler:
    handler: landsat_mosaic_tiler.handlers.tiles.app
    memorySize: 3008
    timeout: 20
    layers:
      - arn:aws:lambda:${self:provider.region}:524387336408:layer:gdal24-py37-geolayer:1
    environment:
      CACHE_CONTROL: ${opt:cache-control, 'max-age=3600'}
      CPL_TMPDIR: /tmp
      CPL_VSIL_CURL_ALLOWED_EXTENSIONS: .tif,.TIF,.ovr
      GDAL_CACHEMAX: 25%
      GDAL_DATA: /opt/share/gdal
      GDAL_DISABLE_READDIR_ON_OPEN: FALSE
      GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
      GDAL_HTTP_MULTIPLEX: YES
      GDAL_HTTP_VERSION: 2
      MAX_THREADS: 10
      MOSAIC_DEF_BUCKET: ${opt:bucket}
      PROJ_LIB: /opt/share/proj
      PYTHONWARNINGS: ignore
      VSI_CACHE: TRUE
      VSI_CACHE_SIZE: 536870912
    events:
      - httpApi:
          path: /tiles/{proxy+}
          method: '*'

  mosaics:
    handler: landsat_mosaic_tiler.handlers.mosaic.app
    memorySize: 3008
    timeout: 30
    layers:
      - arn:aws:lambda:${self:provider.region}:524387336408:layer:gdal24-py37-geolayer:1
    environment:
      CACHE_CONTROL: ${opt:cache-control, 'max-age=3600'}
      GDAL_DATA: /opt/share/gdal
      MOSAIC_DEF_BUCKET: ${opt:bucket}
      PROJ_LIB: /opt/share/proj
    events:
      - httpApi:
          path: /mosaic/{proxy+}
          method: '*'

  batch:
      handler: landsat_mosaic_tiler.handlers.tiles.app
      memorySize: 3008
      timeout: 30
      layers:
        - arn:aws:lambda:${self:provider.region}:524387336408:layer:gdal24-py37-geolayer:1
      environment:
        CACHE_CONTROL: ${opt:cache-control, 'max-age=3600'}
        CPL_TMPDIR: /tmp
        CPL_VSIL_CURL_ALLOWED_EXTENSIONS: .tif,.TIF,.ovr
      GDAL_CACHEMAX: 25%
        GDAL_DATA: /opt/share/gdal
        GDAL_DISABLE_READDIR_ON_OPEN: FALSE
        GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
        GDAL_HTTP_MULTIPLEX: YES
        GDAL_HTTP_VERSION: 2
        MAX_THREADS: 20
        MOSAIC_DEF_BUCKET: ${opt:bucket}
        PROJ_LIB: /opt/share/proj
        PYTHONWARNINGS: ignore
        VSI_CACHE: TRUE
        VSI_CACHE_SIZE: 536870912
      events:
        - httpApi:
            path: /batch/{proxy+}
            method: '*'
